pool:
  vmImage: ubuntu-latest
steps:
  - task: InstallMATLAB@0

  # This step creates a new pipeline variable: doThing. This variable will be available to subsquent steps.
  - task: RunMATLABCommand@0
    inputs:
      command: |
        myvalue = "Yes";
        disp("##vso[task.setvariable variable=doThing]" + myvalue);

  # This step is able to use doThing, so it uses it in its condition
  - script: |
      # You can access the variable from Step 1 as an environment variable.
      echo "Value of doThing (as DOTHING env var): $DOTHING."
    condition: and(succeeded(), eq(variables['doThing'], 'Yes')) # or and(succeeded(), eq(variables.doThing, 'Yes'))